database:
  host: localhost
  port: 5432
  dbname: postgres
  user: postgres
  password: postgres

administration:
  base_url: "http://localhost:8081"
  host: "127.0.0.1"
  port: 8081

terminalserver:
  base_url: "http://localhost:8082"
  host: "127.0.0.1"
  port: 8082

core:
  secret_key: "asdf1234"
